### ISSUE TITLE
FYI: Repromise is now reason-promise

### ISSUE THREAD

**Issue by aantron** [dariusf/dariusf.github.io#1]
In reference to https://github.com/dariusf/dariusf.github.io/blame/9977b3301b3a9641d6219b0045501d6c5d999673/_posts/2018-02-18-reason-for-ocaml-devs.md#L173.

reason-promise cleans up the API and makes it nicer, adds helpers for `Result` and `Option`, and fixes bugs, including enough bundle size bugs that it is now 1K bundled. See the [repo](https://github.com/aantron/promise) and [recent releases](https://github.com/aantron/promise/releases).

**Comment by dariusf** [comment]
Thanks!
